

spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webfluxcluster.cvtna.mongodb.net/${DB_NAME:webflux}?retryWrites=true&w=majority&appName=WebfluxCluster
      auto-index-creation: true

  application:
    name: webflux